base_url = "https://www.francoislancelot.com"
title = "François Lancelot"
compile_sass = true
theme = "apollo"
build_search_index = true
generate_feed = true
minify_html = true

[markdown]
highlight_code = true
render_emoji = true

[extra]
toc = false
use_cdn = false
favicon = "/icon/favicon.ico"
theme = "toggle"

menu = [
    { name = "/about", url = "/about", weight = 1 },
]

socials = [
    { name = "github", url = "https://github.com/francoislanc", icon = "github" },
    { name = "google-scholar", url = "https://scholar.google.fr/citations?user=XUGOVcoAAAAJ&hl=en", icon = "google-scholar" },
    { name = "linkedin", url = "https://www.linkedin.com/in/francois-lancelot-aa049641", icon = "linkedin" },
]

custom_css = []
